
GET http://localhost:4000/Users

####

POST http://localhost:4000/AddUser
Content-Type: application/json

{
    "name": "Alejandro",
    "role": "User",
    "lastname": "Silva",
    "country": "Ecuador",
    "email": "pablo.chasipanta@gmail.com",
    "password": "654321"
}

###
// colocar el id para que regrese
GET http://localhost:4000/UserProfile/65238d7ed5dafcc0f4dc1584

###
DELETE http://localhost:4000/UserProfile/65238e2c399e3c8187fc01c7

###
PUT http://localhost:4000/UserProfile/65238d7ed5dafcc0f4dc1584
Content-Type: application/json 

{
    "lastname": "Chasipanta"
}


