
GET http://localhost:4000/Users

####

POST http://localhost:4000/AddUser
Content-Type: application/json

{

    "name": "Alejandro",
    "role": "User",
    "lastname": "Silva",
    "country": "Japon",
    "email": "Alejo@gmail.com",
    "password": "12345",
    "companyName": "XPC",
    "points": 200  

}

###
// colocar el id para que regrese
GET http://localhost:4000/UserProfile/658b17293cf836c457e9f6b8

###
DELETE http://localhost:4000/UserProfile/65282f7bd0a5462192377997

###
PUT http://localhost:4000/UserProfile/6526f397e83abf69216cd349
Content-Type: application/json 

{
    "lastname": "Chasipanta"
}
### 

GET http://localhost:4000/SearchUserProfile/chasi64.z@gmail.com/123456







###

POST http://localhost:4000/User/658b173a3cf836c457e9f6ba/Oportunity
Content-Type: application/json

{

    "IDEmpleado": "",
    "companyName": "SUPER BANCO",
    "country": "Rusia",
    "address": "Calle Principal 123",
    "city": "Ciudad",
    "state": "Estado",
    "postalCode": "12345",
    "clientName": "SEBAS",
    "clientLastName": "ApellidoCliente",
    "title": "TítuloCliente",
    "phone": "123-456-7890",
    "expectedCoseDate": "2023-01-01",
    "currency": "USD",
    "projectDescripcion": "Descripción del proyecto",
    "numberLicense": 543,
    "products": "Productos relacionados",
    "status": "Registrado",
    "Evidence": [
        {
            "nombre": "Documento1",
            "descripcion": "Descripción del documento 1",
            "feedback": "Feedback del documento 1",
            "note": 2,
            "isRequire": true
        },
        {
            "nombre": "Documento2",
            "descripcion": "Descripción del documento 2",
            "feedback": "Feedback del documento 2",
            "note": 3,
            "isRequire": true
        }
    ]
}

###
// obtener todas las oportunidades
GET http://localhost:4000/User/6589d3b041b5706d9375688d/OportunityALL

###

GET http://localhost:4000/GMS/Users/

###

GET http://localhost:4000/GMS/OportunityALL

###

GET http://localhost:4000/GMS/PromOport

### 

GET http://localhost:4000/GMS/NotesOport
